name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image stack
        run: docker-compose up --build --no-start
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v2
      - name: push docker image to docker hub
        run: |
          docker tag chatwoot:latest ${{ secrets.DOCKER_HUB_USERNAME }}/chatwoot:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/chatwoot:latest
